# Gruvdark Dark

cursor                  #E6E3DE
cursor_text_color       #1e1e1e

url_color               #579DD4

visual_bell_color       #72BA62
bell_border_color       #72BA62

active_border_color     #D159B6
inactive_border_color   #404040

foreground              #d6cfc4
background              #1e1e1e
selection_foreground    #D6CFC4
selection_background    #303030

active_tab_foreground   #d6cfc4
active_tab_background   #404040
inactive_tab_foreground #d6cfc4
inactive_tab_background #303030

# black
color0                  #4F4F4F
color8                  #4F4F4F

# red
color1                  #E16464
color9                  #E16464

# green
color2                  #72BA62
color10                 #72BA62

# yellow
color3                  #D19F66
color11                 #D19F66

# blue
color4                  #579DD4
color12                 #579DD4

# purple
color5                  #D159B6
color13                 #D159B6

# aqua
color6                  #00A596
color14                 #00A596

# white
color7                  #D6CFC4
color15                 #D6CFC4
